# DO NOT EDIT THIS FILE!
#
# Python module IEV generated by omniidl

import omniORB
omniORB.updateModule("spell.lib.hifly.interface.IEV")

# ** 1. Stub files contributing to this module
import spell.lib.hifly.interface.IEV_idl

# ** 2. Sub-modules

# ** 3. End
