# DO NOT EDIT THIS FILE!
#
# Python module ITMSET generated by omniidl

import omniORB
omniORB.updateModule("spell.lib.hifly.interface.ITMSET")

# ** 1. Stub files contributing to this module
import spell.lib.hifly.interface.ITMSET_idl

# ** 2. Sub-modules

# ** 3. End
