# DO NOT EDIT THIS FILE!
#
# Python module ITC generated by omniidl

import omniORB
omniORB.updateModule("spell.lib.hifly.interface.ITC")

# ** 1. Stub files contributing to this module
import spell.lib.hifly.interface.ITC_idl

# ** 2. Sub-modules

# ** 3. End
