# DO NOT EDIT THIS FILE!
#
# Python module ITM generated by omniidl

import omniORB
omniORB.updateModule("spell.lib.hifly.interface.ITM")

# ** 1. Stub files contributing to this module
import spell.lib.hifly.interface.ITM_idl

# ** 2. Sub-modules

# ** 3. End
