# DO NOT EDIT THIS FILE!
#
# Python module IMIB generated by omniidl

import omniORB
omniORB.updateModule("spell.lib.hifly.interface.IMIB")

# ** 1. Stub files contributing to this module
import spell.lib.hifly.interface.IMIB_idl

# ** 2. Sub-modules

# ** 3. End
