# Python stubs generated by omniidl from TKCOMcorbaGUIinterest.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "_GlobalIDL"
#
__name__ = "spell.lib.hifly.interface._GlobalIDL"
_0__GlobalIDL = omniORB.openModule("spell.lib.hifly.interface._GlobalIDL", r"TKCOMcorbaGUIinterest.idl")
_0__GlobalIDL__POA = omniORB.openModule("spell.lib.hifly.interface._GlobalIDL__POA", r"TKCOMcorbaGUIinterest.idl")


# interface TKCOMcorbaGUIinterest
_0__GlobalIDL._d_TKCOMcorbaGUIinterest = (omniORB.tcInternal.tv_objref, "IDL:TKCOMcorbaGUIinterest:1.0", "TKCOMcorbaGUIinterest")
omniORB.typeMapping["IDL:TKCOMcorbaGUIinterest:1.0"] = _0__GlobalIDL._d_TKCOMcorbaGUIinterest
_0__GlobalIDL.TKCOMcorbaGUIinterest = omniORB.newEmptyClass()
class TKCOMcorbaGUIinterest :
    _NP_RepositoryId = _0__GlobalIDL._d_TKCOMcorbaGUIinterest[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0__GlobalIDL.TKCOMcorbaGUIinterest = TKCOMcorbaGUIinterest
_0__GlobalIDL._tc_TKCOMcorbaGUIinterest = omniORB.tcInternal.createTypeCode(_0__GlobalIDL._d_TKCOMcorbaGUIinterest)
omniORB.registerType(TKCOMcorbaGUIinterest._NP_RepositoryId, _0__GlobalIDL._d_TKCOMcorbaGUIinterest, _0__GlobalIDL._tc_TKCOMcorbaGUIinterest)

# TKCOMcorbaGUIinterest operations and attributes
TKCOMcorbaGUIinterest._d_applicationStopped = ((omniORB.tcInternal.tv_short, ), None, None)
TKCOMcorbaGUIinterest._d_applicationStarting = ((omniORB.tcInternal.tv_short, ), None, None)
TKCOMcorbaGUIinterest._d_applicationStarted = ((omniORB.tcInternal.tv_short, ), None, None)
TKCOMcorbaGUIinterest._d_applicationDied = ((omniORB.tcInternal.tv_short, ), None, None)
TKCOMcorbaGUIinterest._d_applicationUnknown = ((omniORB.tcInternal.tv_short, ), None, None)
TKCOMcorbaGUIinterest._d_alive = ((), None, None)

# TKCOMcorbaGUIinterest object reference
class _objref_TKCOMcorbaGUIinterest (CORBA.Object):
    _NP_RepositoryId = TKCOMcorbaGUIinterest._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def applicationStopped(self, *args):
        return _omnipy.invoke(self, "applicationStopped", _0__GlobalIDL.TKCOMcorbaGUIinterest._d_applicationStopped, args)

    def applicationStarting(self, *args):
        return _omnipy.invoke(self, "applicationStarting", _0__GlobalIDL.TKCOMcorbaGUIinterest._d_applicationStarting, args)

    def applicationStarted(self, *args):
        return _omnipy.invoke(self, "applicationStarted", _0__GlobalIDL.TKCOMcorbaGUIinterest._d_applicationStarted, args)

    def applicationDied(self, *args):
        return _omnipy.invoke(self, "applicationDied", _0__GlobalIDL.TKCOMcorbaGUIinterest._d_applicationDied, args)

    def applicationUnknown(self, *args):
        return _omnipy.invoke(self, "applicationUnknown", _0__GlobalIDL.TKCOMcorbaGUIinterest._d_applicationUnknown, args)

    def alive(self, *args):
        return _omnipy.invoke(self, "alive", _0__GlobalIDL.TKCOMcorbaGUIinterest._d_alive, args)

    __methods__ = ["applicationStopped", "applicationStarting", "applicationStarted", "applicationDied", "applicationUnknown", "alive"] + CORBA.Object.__methods__

omniORB.registerObjref(TKCOMcorbaGUIinterest._NP_RepositoryId, _objref_TKCOMcorbaGUIinterest)
_0__GlobalIDL._objref_TKCOMcorbaGUIinterest = _objref_TKCOMcorbaGUIinterest
del TKCOMcorbaGUIinterest, _objref_TKCOMcorbaGUIinterest

# TKCOMcorbaGUIinterest skeleton
__name__ = "spell.lib.hifly.interface._GlobalIDL__POA"
class TKCOMcorbaGUIinterest (PortableServer.Servant):
    _NP_RepositoryId = _0__GlobalIDL.TKCOMcorbaGUIinterest._NP_RepositoryId


    _omni_op_d = {"applicationStopped": _0__GlobalIDL.TKCOMcorbaGUIinterest._d_applicationStopped, "applicationStarting": _0__GlobalIDL.TKCOMcorbaGUIinterest._d_applicationStarting, "applicationStarted": _0__GlobalIDL.TKCOMcorbaGUIinterest._d_applicationStarted, "applicationDied": _0__GlobalIDL.TKCOMcorbaGUIinterest._d_applicationDied, "applicationUnknown": _0__GlobalIDL.TKCOMcorbaGUIinterest._d_applicationUnknown, "alive": _0__GlobalIDL.TKCOMcorbaGUIinterest._d_alive}

TKCOMcorbaGUIinterest._omni_skeleton = TKCOMcorbaGUIinterest
_0__GlobalIDL__POA.TKCOMcorbaGUIinterest = TKCOMcorbaGUIinterest
omniORB.registerSkeleton(TKCOMcorbaGUIinterest._NP_RepositoryId, TKCOMcorbaGUIinterest)
del TKCOMcorbaGUIinterest
__name__ = "spell.lib.hifly.interface._GlobalIDL"

#
# End of module "_GlobalIDL"
#
__name__ = "spell.lib.hifly.interface.TKCOMcorbaGUIinterest_idl"

_exported_modules = ( "spell.lib.hifly.interface._GlobalIDL", )

# The end.
