# Python stubs generated by omniidl from TKCOMcorbaProcessList.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "_GlobalIDL"
#
__name__ = "spell.lib.hifly.interface._GlobalIDL"
_0__GlobalIDL = omniORB.openModule("spell.lib.hifly.interface._GlobalIDL", r"TKCOMcorbaProcessList.idl")
_0__GlobalIDL__POA = omniORB.openModule("spell.lib.hifly.interface._GlobalIDL__POA", r"TKCOMcorbaProcessList.idl")

# #include "TKCOM/TKCOMcorbaGUIinstallation.idl"
import spell.lib.hifly.interface.TKCOMcorbaGUIinstallation_idl
# #include "TKCOM/TKCOMcorbaGUIinterest.idl"
import spell.lib.hifly.interface.TKCOMcorbaGUIinterest_idl
# #include "TKCOM/TKCOMcorbaGUIlogInterest.idl"
import spell.lib.hifly.interface.TKCOMcorbaGUIlogInterest_idl
# #include "TKCOM/TKCOMcorbaApplication.idl"
import spell.lib.hifly.interface.TKCOMcorbaApplication_idl

# interface TKCOMcorbaProcessList
_0__GlobalIDL._d_TKCOMcorbaProcessList = (omniORB.tcInternal.tv_objref, "IDL:TKCOMcorbaProcessList:1.0", "TKCOMcorbaProcessList")
omniORB.typeMapping["IDL:TKCOMcorbaProcessList:1.0"] = _0__GlobalIDL._d_TKCOMcorbaProcessList
_0__GlobalIDL.TKCOMcorbaProcessList = omniORB.newEmptyClass()
class TKCOMcorbaProcessList :
    _NP_RepositoryId = _0__GlobalIDL._d_TKCOMcorbaProcessList[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil

    
    # typedef ... TKCOMenvironment
    class TKCOMenvironment:
        _NP_RepositoryId = "IDL:TKCOMcorbaProcessList/TKCOMenvironment:1.0"
        def __init__(self, *args, **kw):
            raise RuntimeError("Cannot construct objects of this type.")
    _d_TKCOMenvironment  = (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0)
    _ad_TKCOMenvironment = (omniORB.tcInternal.tv_alias, TKCOMenvironment._NP_RepositoryId, "TKCOMenvironment", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0))
    _tc_TKCOMenvironment = omniORB.tcInternal.createTypeCode(_ad_TKCOMenvironment)
    omniORB.registerType(TKCOMenvironment._NP_RepositoryId, _ad_TKCOMenvironment, _tc_TKCOMenvironment)


_0__GlobalIDL.TKCOMcorbaProcessList = TKCOMcorbaProcessList
_0__GlobalIDL._tc_TKCOMcorbaProcessList = omniORB.tcInternal.createTypeCode(_0__GlobalIDL._d_TKCOMcorbaProcessList)
omniORB.registerType(TKCOMcorbaProcessList._NP_RepositoryId, _0__GlobalIDL._d_TKCOMcorbaProcessList, _0__GlobalIDL._tc_TKCOMcorbaProcessList)

# TKCOMcorbaProcessList operations and attributes
TKCOMcorbaProcessList._d_appInterestedIn = ((omniORB.typeMapping["IDL:TKCOMcorbaGUIinstallation:1.0"], ), (omniORB.tcInternal.tv_boolean, ), None)
TKCOMcorbaProcessList._d_GUIinterestedIn = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_short, omniORB.typeMapping["IDL:TKCOMcorbaGUIinterest:1.0"], (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_boolean), (omniORB.tcInternal.tv_boolean, ), None)
TKCOMcorbaProcessList._d_hasInstanceStarted = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
TKCOMcorbaProcessList._d_GUIlogInterestIn = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_short, omniORB.typeMapping["IDL:TKCOMcorbaGUIlogInterest:1.0"], (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
TKCOMcorbaProcessList._d_isFamily = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_short, (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
TKCOMcorbaProcessList._d_startProcess = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_short, (omniORB.tcInternal.tv_string,0), omniORB.typeMapping["IDL:TKCOMcorbaProcessList/TKCOMenvironment:1.0"], omniORB.tcInternal.tv_short, (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
TKCOMcorbaProcessList._d_deIconiseProcess = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_short, (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
TKCOMcorbaProcessList._d_stopProcess = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_boolean, (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
TKCOMcorbaProcessList._d_resetProcess = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_short, (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), None)
TKCOMcorbaProcessList._d_setRestartArgs = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
TKCOMcorbaProcessList._d_stopHost = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_boolean), (omniORB.tcInternal.tv_boolean, ), None)
TKCOMcorbaProcessList._d_makeOperational = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
TKCOMcorbaProcessList._d_gracefulDeath = ((omniORB.tcInternal.tv_long, ), (), None)
TKCOMcorbaProcessList._d_processStarted = ((omniORB.tcInternal.tv_long, ), (), None)
TKCOMcorbaProcessList._d_registerApplication = ((omniORB.tcInternal.tv_long, omniORB.typeMapping["IDL:TKCOMcorbaApplication:1.0"]), (omniORB.tcInternal.tv_boolean, ), None)
TKCOMcorbaProcessList._d_setServerFamily = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_short, (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), None)
TKCOMcorbaProcessList._d_alive = ((), (), None)
TKCOMcorbaProcessList._d_getText = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), None)

# TKCOMcorbaProcessList object reference
class _objref_TKCOMcorbaProcessList (CORBA.Object):
    _NP_RepositoryId = TKCOMcorbaProcessList._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def appInterestedIn(self, *args):
        return _omnipy.invoke(self, "appInterestedIn", _0__GlobalIDL.TKCOMcorbaProcessList._d_appInterestedIn, args)

    def GUIinterestedIn(self, *args):
        return _omnipy.invoke(self, "GUIinterestedIn", _0__GlobalIDL.TKCOMcorbaProcessList._d_GUIinterestedIn, args)

    def hasInstanceStarted(self, *args):
        return _omnipy.invoke(self, "hasInstanceStarted", _0__GlobalIDL.TKCOMcorbaProcessList._d_hasInstanceStarted, args)

    def GUIlogInterestIn(self, *args):
        return _omnipy.invoke(self, "GUIlogInterestIn", _0__GlobalIDL.TKCOMcorbaProcessList._d_GUIlogInterestIn, args)

    def isFamily(self, *args):
        return _omnipy.invoke(self, "isFamily", _0__GlobalIDL.TKCOMcorbaProcessList._d_isFamily, args)

    def startProcess(self, *args):
        return _omnipy.invoke(self, "startProcess", _0__GlobalIDL.TKCOMcorbaProcessList._d_startProcess, args)

    def deIconiseProcess(self, *args):
        return _omnipy.invoke(self, "deIconiseProcess", _0__GlobalIDL.TKCOMcorbaProcessList._d_deIconiseProcess, args)

    def stopProcess(self, *args):
        return _omnipy.invoke(self, "stopProcess", _0__GlobalIDL.TKCOMcorbaProcessList._d_stopProcess, args)

    def resetProcess(self, *args):
        return _omnipy.invoke(self, "resetProcess", _0__GlobalIDL.TKCOMcorbaProcessList._d_resetProcess, args)

    def setRestartArgs(self, *args):
        return _omnipy.invoke(self, "setRestartArgs", _0__GlobalIDL.TKCOMcorbaProcessList._d_setRestartArgs, args)

    def stopHost(self, *args):
        return _omnipy.invoke(self, "stopHost", _0__GlobalIDL.TKCOMcorbaProcessList._d_stopHost, args)

    def makeOperational(self, *args):
        return _omnipy.invoke(self, "makeOperational", _0__GlobalIDL.TKCOMcorbaProcessList._d_makeOperational, args)

    def gracefulDeath(self, *args):
        return _omnipy.invoke(self, "gracefulDeath", _0__GlobalIDL.TKCOMcorbaProcessList._d_gracefulDeath, args)

    def processStarted(self, *args):
        return _omnipy.invoke(self, "processStarted", _0__GlobalIDL.TKCOMcorbaProcessList._d_processStarted, args)

    def registerApplication(self, *args):
        return _omnipy.invoke(self, "registerApplication", _0__GlobalIDL.TKCOMcorbaProcessList._d_registerApplication, args)

    def setServerFamily(self, *args):
        return _omnipy.invoke(self, "setServerFamily", _0__GlobalIDL.TKCOMcorbaProcessList._d_setServerFamily, args)

    def alive(self, *args):
        return _omnipy.invoke(self, "alive", _0__GlobalIDL.TKCOMcorbaProcessList._d_alive, args)

    def getText(self, *args):
        return _omnipy.invoke(self, "getText", _0__GlobalIDL.TKCOMcorbaProcessList._d_getText, args)

    __methods__ = ["appInterestedIn", "GUIinterestedIn", "hasInstanceStarted", "GUIlogInterestIn", "isFamily", "startProcess", "deIconiseProcess", "stopProcess", "resetProcess", "setRestartArgs", "stopHost", "makeOperational", "gracefulDeath", "processStarted", "registerApplication", "setServerFamily", "alive", "getText"] + CORBA.Object.__methods__

omniORB.registerObjref(TKCOMcorbaProcessList._NP_RepositoryId, _objref_TKCOMcorbaProcessList)
_0__GlobalIDL._objref_TKCOMcorbaProcessList = _objref_TKCOMcorbaProcessList
del TKCOMcorbaProcessList, _objref_TKCOMcorbaProcessList

# TKCOMcorbaProcessList skeleton
__name__ = "spell.lib.hifly.interface._GlobalIDL__POA"
class TKCOMcorbaProcessList (PortableServer.Servant):
    _NP_RepositoryId = _0__GlobalIDL.TKCOMcorbaProcessList._NP_RepositoryId


    _omni_op_d = {"appInterestedIn": _0__GlobalIDL.TKCOMcorbaProcessList._d_appInterestedIn, "GUIinterestedIn": _0__GlobalIDL.TKCOMcorbaProcessList._d_GUIinterestedIn, "hasInstanceStarted": _0__GlobalIDL.TKCOMcorbaProcessList._d_hasInstanceStarted, "GUIlogInterestIn": _0__GlobalIDL.TKCOMcorbaProcessList._d_GUIlogInterestIn, "isFamily": _0__GlobalIDL.TKCOMcorbaProcessList._d_isFamily, "startProcess": _0__GlobalIDL.TKCOMcorbaProcessList._d_startProcess, "deIconiseProcess": _0__GlobalIDL.TKCOMcorbaProcessList._d_deIconiseProcess, "stopProcess": _0__GlobalIDL.TKCOMcorbaProcessList._d_stopProcess, "resetProcess": _0__GlobalIDL.TKCOMcorbaProcessList._d_resetProcess, "setRestartArgs": _0__GlobalIDL.TKCOMcorbaProcessList._d_setRestartArgs, "stopHost": _0__GlobalIDL.TKCOMcorbaProcessList._d_stopHost, "makeOperational": _0__GlobalIDL.TKCOMcorbaProcessList._d_makeOperational, "gracefulDeath": _0__GlobalIDL.TKCOMcorbaProcessList._d_gracefulDeath, "processStarted": _0__GlobalIDL.TKCOMcorbaProcessList._d_processStarted, "registerApplication": _0__GlobalIDL.TKCOMcorbaProcessList._d_registerApplication, "setServerFamily": _0__GlobalIDL.TKCOMcorbaProcessList._d_setServerFamily, "alive": _0__GlobalIDL.TKCOMcorbaProcessList._d_alive, "getText": _0__GlobalIDL.TKCOMcorbaProcessList._d_getText}

TKCOMcorbaProcessList._omni_skeleton = TKCOMcorbaProcessList
_0__GlobalIDL__POA.TKCOMcorbaProcessList = TKCOMcorbaProcessList
omniORB.registerSkeleton(TKCOMcorbaProcessList._NP_RepositoryId, TKCOMcorbaProcessList)
del TKCOMcorbaProcessList
__name__ = "spell.lib.hifly.interface._GlobalIDL"

#
# End of module "_GlobalIDL"
#
__name__ = "spell.lib.hifly.interface.TKCOMcorbaProcessList_idl"

_exported_modules = ( "spell.lib.hifly.interface._GlobalIDL", )

# The end.
