# Python stubs generated by omniidl from USERcorbaManagerSync.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "_GlobalIDL"
#
__name__ = "spell.lib.hifly.interface._GlobalIDL"
_0__GlobalIDL = omniORB.openModule("spell.lib.hifly.interface._GlobalIDL", r"USERcorbaManagerSync.idl")
_0__GlobalIDL__POA = omniORB.openModule("spell.lib.hifly.interface._GlobalIDL__POA", r"USERcorbaManagerSync.idl")

# #include "USER/USERcorbaTypes.idl"
import spell.lib.hifly.interface.USERcorbaTypes_idl
# #include "USER/USERcorbaNotificationSource.idl"
import spell.lib.hifly.interface.USERcorbaNotificationSource_idl
# #include "USER/USERcorbaSession.idl"
import spell.lib.hifly.interface.USERcorbaSession_idl
# #include "USER/USERcorbaManager.idl"
import spell.lib.hifly.interface.USERcorbaManager_idl

# struct EventMessage
_0__GlobalIDL.EventMessage = omniORB.newEmptyClass()
class EventMessage (omniORB.StructBase):
    _NP_RepositoryId = "IDL:EventMessage:1.0"

    def __init__(self, timeStamp, evType, message):
        self.timeStamp = timeStamp
        self.evType = evType
        self.message = message

_0__GlobalIDL.EventMessage = EventMessage
_0__GlobalIDL._d_EventMessage  = (omniORB.tcInternal.tv_struct, EventMessage, EventMessage._NP_RepositoryId, "EventMessage", "timeStamp", omniORB.typeMapping["IDL:USERtime:1.0"], "evType", omniORB.typeMapping["IDL:UserEventType:1.0"], "message", (omniORB.tcInternal.tv_string,0))
_0__GlobalIDL._tc_EventMessage = omniORB.tcInternal.createTypeCode(_0__GlobalIDL._d_EventMessage)
omniORB.registerType(EventMessage._NP_RepositoryId, _0__GlobalIDL._d_EventMessage, _0__GlobalIDL._tc_EventMessage)
del EventMessage

# struct USERconfiguration
_0__GlobalIDL.USERconfiguration = omniORB.newEmptyClass()
class USERconfiguration (omniORB.StructBase):
    _NP_RepositoryId = "IDL:USERconfiguration:1.0"

    def __init__(self, timeStamp, privileges, roles, profiles, workstations, activeSessions):
        self.timeStamp = timeStamp
        self.privileges = privileges
        self.roles = roles
        self.profiles = profiles
        self.workstations = workstations
        self.activeSessions = activeSessions

_0__GlobalIDL.USERconfiguration = USERconfiguration
_0__GlobalIDL._d_USERconfiguration  = (omniORB.tcInternal.tv_struct, USERconfiguration, USERconfiguration._NP_RepositoryId, "USERconfiguration", "timeStamp", omniORB.typeMapping["IDL:USERtime:1.0"], "privileges", omniORB.typeMapping["IDL:USERcorbaStringMap:1.0"], "roles", omniORB.typeMapping["IDL:USERcorbaStringListMapSequence:1.0"], "profiles", omniORB.typeMapping["IDL:USERcorbaProfileDataSequence:1.0"], "workstations", omniORB.typeMapping["IDL:USERcorbaStringMap:1.0"], "activeSessions", omniORB.typeMapping["IDL:USERcorbaActiveSessionDataSequence:1.0"])
_0__GlobalIDL._tc_USERconfiguration = omniORB.tcInternal.createTypeCode(_0__GlobalIDL._d_USERconfiguration)
omniORB.registerType(USERconfiguration._NP_RepositoryId, _0__GlobalIDL._d_USERconfiguration, _0__GlobalIDL._tc_USERconfiguration)
del USERconfiguration

# interface USERcorbaManagerSync
_0__GlobalIDL._d_USERcorbaManagerSync = (omniORB.tcInternal.tv_objref, "IDL:USERcorbaManagerSync:1.0", "USERcorbaManagerSync")
omniORB.typeMapping["IDL:USERcorbaManagerSync:1.0"] = _0__GlobalIDL._d_USERcorbaManagerSync
_0__GlobalIDL.USERcorbaManagerSync = omniORB.newEmptyClass()
class USERcorbaManagerSync (_0__GlobalIDL.USERcorbaManager):
    _NP_RepositoryId = _0__GlobalIDL._d_USERcorbaManagerSync[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0__GlobalIDL.USERcorbaManagerSync = USERcorbaManagerSync
_0__GlobalIDL._tc_USERcorbaManagerSync = omniORB.tcInternal.createTypeCode(_0__GlobalIDL._d_USERcorbaManagerSync)
omniORB.registerType(USERcorbaManagerSync._NP_RepositoryId, _0__GlobalIDL._d_USERcorbaManagerSync, _0__GlobalIDL._tc_USERcorbaManagerSync)

# USERcorbaManagerSync operations and attributes
USERcorbaManagerSync._d_updateEvent = ((omniORB.typeMapping["IDL:EventMessage:1.0"], ), (), None)
USERcorbaManagerSync._d_getConfiguration = ((), (omniORB.typeMapping["IDL:USERconfiguration:1.0"], ), None)
USERcorbaManagerSync._d_reloadStaticConfiguration = ((), (), None)

# USERcorbaManagerSync object reference
class _objref_USERcorbaManagerSync (_0__GlobalIDL._objref_USERcorbaManager):
    _NP_RepositoryId = USERcorbaManagerSync._NP_RepositoryId

    def __init__(self):
        _0__GlobalIDL._objref_USERcorbaManager.__init__(self)

    def updateEvent(self, *args):
        return _omnipy.invoke(self, "updateEvent", _0__GlobalIDL.USERcorbaManagerSync._d_updateEvent, args)

    def getConfiguration(self, *args):
        return _omnipy.invoke(self, "getConfiguration", _0__GlobalIDL.USERcorbaManagerSync._d_getConfiguration, args)

    def reloadStaticConfiguration(self, *args):
        return _omnipy.invoke(self, "reloadStaticConfiguration", _0__GlobalIDL.USERcorbaManagerSync._d_reloadStaticConfiguration, args)

    __methods__ = ["updateEvent", "getConfiguration", "reloadStaticConfiguration"] + _0__GlobalIDL._objref_USERcorbaManager.__methods__

omniORB.registerObjref(USERcorbaManagerSync._NP_RepositoryId, _objref_USERcorbaManagerSync)
_0__GlobalIDL._objref_USERcorbaManagerSync = _objref_USERcorbaManagerSync
del USERcorbaManagerSync, _objref_USERcorbaManagerSync

# USERcorbaManagerSync skeleton
__name__ = "spell.lib.hifly.interface._GlobalIDL__POA"
class USERcorbaManagerSync (_0__GlobalIDL__POA.USERcorbaManager):
    _NP_RepositoryId = _0__GlobalIDL.USERcorbaManagerSync._NP_RepositoryId


    _omni_op_d = {"updateEvent": _0__GlobalIDL.USERcorbaManagerSync._d_updateEvent, "getConfiguration": _0__GlobalIDL.USERcorbaManagerSync._d_getConfiguration, "reloadStaticConfiguration": _0__GlobalIDL.USERcorbaManagerSync._d_reloadStaticConfiguration}
    _omni_op_d.update(_0__GlobalIDL__POA.USERcorbaManager._omni_op_d)

USERcorbaManagerSync._omni_skeleton = USERcorbaManagerSync
_0__GlobalIDL__POA.USERcorbaManagerSync = USERcorbaManagerSync
omniORB.registerSkeleton(USERcorbaManagerSync._NP_RepositoryId, USERcorbaManagerSync)
del USERcorbaManagerSync
__name__ = "spell.lib.hifly.interface._GlobalIDL"

#
# End of module "_GlobalIDL"
#
__name__ = "spell.lib.hifly.interface.USERcorbaManagerSync_idl"

_exported_modules = ( "spell.lib.hifly.interface._GlobalIDL", )

# The end.
