# DO NOT EDIT THIS FILE!
#
# Python module _GlobalIDL__POA generated by omniidl

import omniORB
omniORB.updateModule("spell.lib.hifly.interface._GlobalIDL__POA")

# ** 1. Stub files contributing to this module
import spell.lib.hifly.interface.TKCOMcorbaApplication_idl
import spell.lib.hifly.interface.TKCOMcorbaGUI_idl
import spell.lib.hifly.interface.TKCOMcorbaGUIlogInterest_idl
import spell.lib.hifly.interface.TKCOMcorbaGUIinstallation_idl
import spell.lib.hifly.interface.TKCOMcorbaProcessList_idl
import spell.lib.hifly.interface.TKCOMcorbaGUIinterest_idl
import spell.lib.hifly.interface.USERcorbaTypes_idl
import spell.lib.hifly.interface.USERcorbaManagerSync_idl
import spell.lib.hifly.interface.USERcorbaManager_idl
import spell.lib.hifly.interface.USERcorbaNotificationSource_idl
import spell.lib.hifly.interface.USERcorbaSession_idl

# ** 2. Sub-modules

# ** 3. End
