# Python stubs generated by omniidl from TKCOMcorbaGUI.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "_GlobalIDL"
#
__name__ = "spell.lib.hifly.interface._GlobalIDL"
_0__GlobalIDL = omniORB.openModule("spell.lib.hifly.interface._GlobalIDL", r"TKCOMcorbaGUI.idl")
_0__GlobalIDL__POA = omniORB.openModule("spell.lib.hifly.interface._GlobalIDL__POA", r"TKCOMcorbaGUI.idl")


# interface TKCOMcorbaGUI
_0__GlobalIDL._d_TKCOMcorbaGUI = (omniORB.tcInternal.tv_objref, "IDL:TKCOMcorbaGUI:1.0", "TKCOMcorbaGUI")
omniORB.typeMapping["IDL:TKCOMcorbaGUI:1.0"] = _0__GlobalIDL._d_TKCOMcorbaGUI
_0__GlobalIDL.TKCOMcorbaGUI = omniORB.newEmptyClass()
class TKCOMcorbaGUI :
    _NP_RepositoryId = _0__GlobalIDL._d_TKCOMcorbaGUI[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0__GlobalIDL.TKCOMcorbaGUI = TKCOMcorbaGUI
_0__GlobalIDL._tc_TKCOMcorbaGUI = omniORB.tcInternal.createTypeCode(_0__GlobalIDL._d_TKCOMcorbaGUI)
omniORB.registerType(TKCOMcorbaGUI._NP_RepositoryId, _0__GlobalIDL._d_TKCOMcorbaGUI, _0__GlobalIDL._tc_TKCOMcorbaGUI)

# TKCOMcorbaGUI operations and attributes
TKCOMcorbaGUI._d_setActiveDomain = (((omniORB.tcInternal.tv_string,0), ), (), None)
TKCOMcorbaGUI._d_alive = ((), (), None)

# TKCOMcorbaGUI object reference
class _objref_TKCOMcorbaGUI (CORBA.Object):
    _NP_RepositoryId = TKCOMcorbaGUI._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def setActiveDomain(self, *args):
        return _omnipy.invoke(self, "setActiveDomain", _0__GlobalIDL.TKCOMcorbaGUI._d_setActiveDomain, args)

    def alive(self, *args):
        return _omnipy.invoke(self, "alive", _0__GlobalIDL.TKCOMcorbaGUI._d_alive, args)

    __methods__ = ["setActiveDomain", "alive"] + CORBA.Object.__methods__

omniORB.registerObjref(TKCOMcorbaGUI._NP_RepositoryId, _objref_TKCOMcorbaGUI)
_0__GlobalIDL._objref_TKCOMcorbaGUI = _objref_TKCOMcorbaGUI
del TKCOMcorbaGUI, _objref_TKCOMcorbaGUI

# TKCOMcorbaGUI skeleton
__name__ = "spell.lib.hifly.interface._GlobalIDL__POA"
class TKCOMcorbaGUI (PortableServer.Servant):
    _NP_RepositoryId = _0__GlobalIDL.TKCOMcorbaGUI._NP_RepositoryId


    _omni_op_d = {"setActiveDomain": _0__GlobalIDL.TKCOMcorbaGUI._d_setActiveDomain, "alive": _0__GlobalIDL.TKCOMcorbaGUI._d_alive}

TKCOMcorbaGUI._omni_skeleton = TKCOMcorbaGUI
_0__GlobalIDL__POA.TKCOMcorbaGUI = TKCOMcorbaGUI
omniORB.registerSkeleton(TKCOMcorbaGUI._NP_RepositoryId, TKCOMcorbaGUI)
del TKCOMcorbaGUI
__name__ = "spell.lib.hifly.interface._GlobalIDL"

#
# End of module "_GlobalIDL"
#
__name__ = "spell.lib.hifly.interface.TKCOMcorbaGUI_idl"

_exported_modules = ( "spell.lib.hifly.interface._GlobalIDL", )

# The end.
