# DO NOT EDIT THIS FILE!
#
# Python module IEV_INJ generated by omniidl

import omniORB
omniORB.updateModule("spell.lib.hifly.interface.IEV_INJ")

# ** 1. Stub files contributing to this module
import spell.lib.hifly.interface.IEV_INJ_idl

# ** 2. Sub-modules

# ** 3. End
