# DO NOT EDIT THIS FILE!
#
# Python module IMEM generated by omniidl

import omniORB
omniORB.updateModule("spell.lib.hifly.interface.IMEM")

# ** 1. Stub files contributing to this module
import spell.lib.hifly.interface.IMEM_idl

# ** 2. Sub-modules

# ** 3. End
