# DO NOT EDIT THIS FILE!
#
# Python module IOFF_AL__POA generated by omniidl

import omniORB
omniORB.updateModule("spell.lib.hifly.interface.IOFF_AL__POA")

# ** 1. Stub files contributing to this module
import spell.lib.hifly.interface.IOFF_AL_idl

# ** 2. Sub-modules

# ** 3. End
