# DO NOT EDIT THIS FILE!
#
# Python module IBASE_IF__POA generated by omniidl

import omniORB
omniORB.updateModule("spell.lib.hifly.interface.IBASE_IF__POA")

# ** 1. Stub files contributing to this module
import spell.lib.hifly.interface.IBASE_IF_idl

# ** 2. Sub-modules

# ** 3. End
