# DO NOT EDIT THIS FILE!
#
# Python module IAUTH generated by omniidl

import omniORB
omniORB.updateModule("spell.lib.hifly.interface.IAUTH")

# ** 1. Stub files contributing to this module
import spell.lib.hifly.interface.IAUTH_idl

# ** 2. Sub-modules

# ** 3. End
