# DO NOT EDIT THIS FILE!
#
# Python module IBASE generated by omniidl

import omniORB
omniORB.updateModule("spell.lib.hifly.interface.IBASE")

# ** 1. Stub files contributing to this module
import spell.lib.hifly.interface.IBASE_idl

# ** 2. Sub-modules

# ** 3. End
