# DO NOT EDIT THIS FILE!
#
# Python module IEV_PRO__POA generated by omniidl

import omniORB
omniORB.updateModule("spell.lib.hifly.interface.IEV_PRO__POA")

# ** 1. Stub files contributing to this module
import spell.lib.hifly.interface.IEV_PRO_idl

# ** 2. Sub-modules

# ** 3. End
