# DO NOT EDIT THIS FILE!
#
# Python module ICR generated by omniidl

import omniORB
omniORB.updateModule("spell.lib.hifly.interface.ICR")

# ** 1. Stub files contributing to this module
import spell.lib.hifly.interface.ICR_idl

# ** 2. Sub-modules

# ** 3. End
